name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Verify project structure
      run: |
        echo "Current directory structure:"
        find . -type f -name "*.py"
        echo "\nChecking for __init__.py files:"
        find src -type f -name "__init__.py"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements-test.txt
        # Install in develop mode with verbose output
        pip install -v -e .

    - name: Verify package installation
      run: |
        echo "Installed packages:"
        pip list
        echo "\nTrying to import the package:"
        python -c "import src; print('src package location:', src.__file__)"
        python -c "from src.data import dataset; print('dataset module location:', dataset.__file__)"

    - name: Run parameter count and accuracy tests
      run: |
        PYTHONPATH="${PYTHONPATH}:${PWD}" pytest tests/test_model_requirements.py -v --import-mode=importlib