name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements-test.txt
        pip install -e .

    - name: List directory structure
      run: |
        tree -a || (apt-get update && apt-get install -y tree && tree -a)

    - name: Run parameter count and accuracy tests
      working-directory: .
      run: |
        python -c "import sys; print(sys.path)"
        pytest tests/test_model_requirements.py -v --import-mode=importlib